Repository zixuan75/html_project, pull requests merged in 2018-03, with the labels that each got.

#47 Our complete branch
  README.md
Labels: enhancement, help wanted, help wanted to issues and pull requests., relabel assignee

#13 Update README.md
  .circleci/config.yml
  .gitignore
  .travis.yml
  1.png
  LICENSE
  README.md
  _config.yml
  app/javascript/index.js
  app/json/collector.json
  buildApplication/applications/app.js
  buildApplication/applications/build.js
  buildApplication/readme.md
  favicon.ico
  globalFolder/duplicate/favicon-ico.js
  globalFolder/global.js
  globalFolder/node_modules/ports.js
  globalFolder/node_modules/text-component.js
  globalFolder/node_modules/text-registered-users/creator.js
  globalFolder/node_modules/text-registered-users/deletor.js
  globalFolder/node_modules/text-registered-users/editor.js
  globalFolder/node_modules/text-unregistered-users/editor.js
  globalFolder/route.js
  globalFolder/scm_modules/collection/post.js
  globalFolder/scm_modules/favicon-js/real/favicon.js
  globalFolder/scm_modules/read.js
  html/attributes/javascript-project/server.js
  html/contest.json
  html/contrastes.json
  html/node-master.html
  javascript/collectors/jsx/InsertComponents.jsx
  javascript/collectors/network.js
  javascript/components/functionalNetworkComponents.js
  javascript/components/jsx/NetworkComponents.jsx
  javascript/components/mainComponents.js
  javascript/embed/insertPosts.js
  javascript/embed/posts.js
  javascript/embed/server/accept.js
  javascript/embed/server/server.jsx
  javascript/node-field.js
  javascript/node-master.js
  javascript/node-plus.js
  projects/conflicts.py
  projects/makefile
  pushed/conflicts/web-application.js
  pushed/conflicts/web-site.js/website.js
  release.com.text
  source/js/conflicts.js
  source/js/pushConflicts.js
Labels: atom-editor, documentation issues, enhancement

#75 Update README
  README.md
Labels: documentation issues, enhancement
